theme = "material_oceanic"


[editor]
cursor-shape.normal = "block"
cursor-shape.insert = "bar"
cursor-shape.select = "underline"
# rainbow-brackets = true

[keys.insert]
"C-[" = "normal_mode"
"C-m" = "insert_newline"
"C-space" = "completion"
"C-e" = "goto_line_end"
"C-b" = "move_char_left"
"C-f" = "move_char_right"

[keys.normal]
C-y = "scroll_up"
D   = "kill_to_line_end"
x = "extend_line_below"
X = "extend_line_above"
space.g.f = ":sh gh browse \"%{buffer_name}\""
space.g.s = ":sh gh browse \"%{buffer_name}:%{selection_line_start}-%{selection_line_end}\""
space.g.c = ":sh echo \"%{buffer_name}:%{selection_line_start}-%{selection_line_end}\" | pbcopy"

[keys.select]
space.g.f = ":sh gh browse \"%{buffer_name}\""
space.g.s = ":sh gh browse \"%{buffer_name}:%{selection_line_start}-%{selection_line_end}\""
space.g.c = ":sh echo \"%{buffer_name}:%{selection_line_start}-%{selection_line_end}\" | pbcopy"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.lsp]
snippets = false
