[[language]]
name = "java"
language-servers = ["jdtls"]

[language-server.jdtls]
command = "jdtls"
args = ["--java-executable", "/Users/hirofumiomi/.local/share/mise/installs/java/21/bin/java"]

[language-server.angular-ls]
command = "/Users/hirofumi.omi/dotfiles/bin/hx-ngserver-global"
required-root-patterns = ["angular.json", "project.json"]

file-types = ["ts", "typescript", "html"]

[language-server.typescript-language-server]
command = "/Users/hirofumi.omi/dotfiles/bin/hx-typescript-language-server-global"
required-root-patterns = ["package.json", "tsconfig.json", "jsconfig.json"]

[[language]]
name = "typescript"
language-servers = ["angular-ls", "typescript-language-server"]

[[language]]
name = "html"
language-servers = ["angular-ls", "vscode-html-languageservice"]

[language-server.kakehashi]
command = "kakehashi"

[[language]]
name = "markdown"
language-servers = ["kakehashi"]
